## Importing the Libraries

In [116]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Importing the Data Set

In [117]:
dataset = pd.read_csv('datasets_4458_8204_winequality-red.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

### Reshaping Dependant Variable

In [118]:
y = y.reshape(len(y), 1)

## Splitting the Dataset into Test Set and Train Set

In [119]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [120]:
print(y_test)

[[6]
 [5]
 [7]
 [6]
 [5]
 [6]
 [5]
 [6]
 [4]
 [5]
 [5]
 [5]
 [6]
 [5]
 [6]
 [6]
 [7]
 [5]
 [5]
 [4]
 [7]
 [6]
 [6]
 [4]
 [6]
 [5]
 [5]
 [7]
 [5]
 [6]
 [5]
 [6]
 [5]
 [6]
 [7]
 [7]
 [5]
 [6]
 [6]
 [7]
 [5]
 [7]
 [6]
 [6]
 [5]
 [5]
 [6]
 [6]
 [6]
 [5]
 [5]
 [5]
 [6]
 [6]
 [6]
 [5]
 [5]
 [5]
 [6]
 [5]
 [5]
 [6]
 [6]
 [6]
 [5]
 [6]
 [5]
 [5]
 [6]
 [6]
 [6]
 [6]
 [4]
 [6]
 [5]
 [6]
 [5]
 [5]
 [5]
 [6]
 [6]
 [5]
 [6]
 [6]
 [6]
 [5]
 [6]
 [5]
 [5]
 [5]
 [5]
 [6]
 [4]
 [5]
 [7]
 [6]
 [6]
 [5]
 [6]
 [5]
 [8]
 [6]
 [6]
 [6]
 [5]
 [5]
 [5]
 [5]
 [7]
 [5]
 [6]
 [5]
 [7]
 [5]
 [6]
 [6]
 [6]
 [7]
 [6]
 [6]
 [5]
 [7]
 [5]
 [5]
 [6]
 [6]
 [5]
 [5]
 [5]
 [6]
 [6]
 [6]
 [6]
 [6]
 [6]
 [5]
 [6]
 [5]
 [8]
 [5]
 [6]
 [5]
 [6]
 [5]
 [4]
 [6]
 [7]
 [6]
 [5]
 [6]
 [6]
 [5]
 [5]
 [5]
 [6]
 [6]
 [3]
 [6]
 [6]
 [6]
 [6]
 [6]
 [6]
 [6]
 [5]
 [5]
 [6]
 [6]
 [6]
 [6]
 [5]
 [5]
 [5]
 [8]
 [5]
 [6]
 [6]
 [7]
 [7]
 [5]
 [5]
 [7]
 [5]
 [6]
 [6]
 [4]
 [5]
 [6]
 [5]
 [5]
 [6]
 [5]
 [6]
 [6]
 [5]
 [5]
 [5]
 [5]
 [5]
 [5]


## Feature Scaling

In [121]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.fit_transform(X_test)

y_train = sc_y.fit_transform(y_train)
y_test = sc_y.fit_transform(y_test)


## Training SVR Model On Train Set

In [122]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(X_train, y_train)

C:\Python\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


SVR()

## Predicting Test Set Results and Comparing

In [123]:
y_pred = regressor.predict(X_test)
y_pred = y_pred.reshape(len(y_pred), 1)

In [124]:
print(np.concatenate((sc_y.inverse_transform(y_test),sc_y.inverse_transform(y_pred)), 1))

[[6.         5.18704203]
 [5.         5.13566432]
 [7.         6.92750945]
 [6.         4.82266403]
 [5.         5.93076789]
 [6.         5.15341262]
 [5.         5.03581956]
 [6.         5.82537685]
 [4.         5.11279564]
 [5.         5.02909887]
 [5.         4.94764799]
 [5.         5.36464956]
 [6.         5.5223583 ]
 [5.         5.37910332]
 [6.         5.42895647]
 [6.         6.21603754]
 [7.         6.80943611]
 [5.         5.27513654]
 [5.         5.39029298]
 [4.         5.2571662 ]
 [7.         5.93687483]
 [6.         5.22703372]
 [6.         5.5939851 ]
 [4.         5.64231643]
 [6.         5.37067678]
 [5.         5.12769018]
 [5.         5.14336341]
 [7.         6.72833462]
 [5.         4.99165024]
 [6.         5.94190318]
 [5.         5.78895461]
 [6.         5.79312761]
 [5.         5.5734269 ]
 [6.         5.39689961]
 [7.         5.91435039]
 [7.         5.95693135]
 [5.         5.25083889]
 [6.         5.78882644]
 [6.         6.08039115]
 [7.         5.80850892]


## Comparing Rounded Results

In [125]:
y_pred_real = sc_y.inverse_transform(y_pred)
y_pred_real = np.round(y_pred_real)
print(np.concatenate((sc_y.inverse_transform(y_test), y_pred_real), 1)) 

[[6. 5.]
 [5. 5.]
 [7. 7.]
 [6. 5.]
 [5. 6.]
 [6. 5.]
 [5. 5.]
 [6. 6.]
 [4. 5.]
 [5. 5.]
 [5. 5.]
 [5. 5.]
 [6. 6.]
 [5. 5.]
 [6. 5.]
 [6. 6.]
 [7. 7.]
 [5. 5.]
 [5. 5.]
 [4. 5.]
 [7. 6.]
 [6. 5.]
 [6. 6.]
 [4. 6.]
 [6. 5.]
 [5. 5.]
 [5. 5.]
 [7. 7.]
 [5. 5.]
 [6. 6.]
 [5. 6.]
 [6. 6.]
 [5. 6.]
 [6. 5.]
 [7. 6.]
 [7. 6.]
 [5. 5.]
 [6. 6.]
 [6. 6.]
 [7. 6.]
 [5. 5.]
 [7. 7.]
 [6. 6.]
 [6. 6.]
 [5. 6.]
 [5. 5.]
 [6. 5.]
 [6. 6.]
 [6. 5.]
 [5. 6.]
 [5. 5.]
 [5. 5.]
 [6. 6.]
 [6. 6.]
 [6. 5.]
 [5. 5.]
 [5. 5.]
 [5. 5.]
 [6. 7.]
 [5. 6.]
 [5. 5.]
 [6. 6.]
 [6. 6.]
 [6. 6.]
 [5. 5.]
 [6. 6.]
 [5. 5.]
 [5. 5.]
 [6. 6.]
 [6. 6.]
 [6. 5.]
 [6. 5.]
 [4. 5.]
 [6. 5.]
 [5. 6.]
 [6. 6.]
 [5. 5.]
 [5. 5.]
 [5. 5.]
 [6. 6.]
 [6. 6.]
 [5. 5.]
 [6. 6.]
 [6. 6.]
 [6. 5.]
 [5. 6.]
 [6. 6.]
 [5. 5.]
 [5. 5.]
 [5. 5.]
 [5. 5.]
 [6. 5.]
 [4. 5.]
 [5. 5.]
 [7. 6.]
 [6. 5.]
 [6. 6.]
 [5. 5.]
 [6. 6.]
 [5. 6.]
 [8. 7.]
 [6. 6.]
 [6. 6.]
 [6. 6.]
 [5. 5.]
 [5. 5.]
 [5. 5.]
 [5. 5.]
 [7. 6.]
 [5. 5.]
 [6. 6.]
 

## Calculating Accuracy

In [126]:
count = 0
for j in range(len(y_test)):
    for i in range(0, 1):
        print(sc_y.inverse_transform(y_test)[j][i])
        print(y_pred_real[j][i])
        if(sc_y.inverse_transform(y_test)[j][i] == y_pred_real[j][i]):
            #print(y_test[j][i] + ' ' + y_pred_real[j][i])
            count = count + 1


6.0
5.0
5.0
5.0
7.0
7.0
6.0
5.0
5.0
6.0
6.0
5.0
5.0
5.0
6.0
6.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
6.0
6.0
5.0
5.0
6.0
5.0
6.0
6.0
7.0
7.0
5.0
5.0
5.0
5.0
4.0
5.0
7.0
6.0
6.0
5.0
6.0
6.0
4.0
6.0
6.0
5.0
5.0
5.0
5.0
5.0
7.0
7.0
5.0
5.0
6.0
6.0
5.0
6.0
6.0
6.0
5.0
6.0
6.0
5.0
7.0
6.0
7.0
6.0
5.0
5.0
6.0
6.0
6.0
6.0
7.0
6.0
5.0
5.0
7.0
7.0
6.0
6.0
6.0
6.0
5.0
6.0
5.0
5.0
6.0
5.0
6.0
6.0
6.0
5.0
5.0
6.0
5.0
5.0
5.0
5.0
6.0
6.0
6.0
6.0
6.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
6.0
7.0
5.0
6.0
5.0
5.0
6.0
6.0
6.0
6.0
6.0
6.0
5.0
5.0
6.0
6.0
5.0
5.0
5.0
5.0
6.0
6.0
6.0
6.0
6.0
5.0
6.0
5.0
4.0
5.0
6.0
5.0
5.0
6.0
6.0
6.0
5.0
5.0
5.0
5.0
5.0
5.0
6.0
6.0
6.0
6.0
5.0
5.0
6.0
6.0
6.0
6.0
6.0
5.0
5.0
6.0
6.0
6.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
6.0
5.0
4.0
5.0
5.0
5.0
7.0
6.0
6.0
5.0
6.0
6.0
5.0
5.0
6.0
6.0
5.0
6.0
8.0
7.0
6.0
6.0
6.0
6.0
6.0
6.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
7.0
6.0
5.0
5.0
6.0
6.0
5.0
5.0
7.0
6.0
5.0
5.0
6.0
6.0
6.0
6.0
6.0
6.0
7.0
7.0
6.0
6.0
6.0
6.0
5.0
5.0
7.0
6.0
5.0
5.0
5.0
5.0
6.0
6.0


## Accuracy for quality prediction

In [129]:
print(count/len(y_test))

0.64375
